### ISSUE TITLE
Impute sex ploidy on dense data

### ISSUE THREAD

**Issue by ch-kr** [broadinstitute/gnomad_methods#135]
The code for sex imputation refinement relies on both chromosome X and chromosome Y ploidy now that https://github.com/macarthur-lab/gnomad_hail/pull/127 has been merged. The code to generate chrX/Y ploidy exists for sparse MatrixTables (https://github.com/macarthur-lab/gnomad_hail/blob/master/utils/sparse_mt.py#L364), but code for dense MatrixTables does not exist.

**Comment by enriquea** [comment]
> The code for sex imputation refinement relies on both chromosome X and chromosome Y ploidy now that #127 has been merged. The code to generate chrX/Y ploidy exists for sparse MatrixTables (https://github.com/macarthur-lab/gnomad_hail/blob/master/utils/sparse_mt.py#L364), but code for dense MatrixTables does not exist.

Hi @ch-kr,
Is there any update to run this code on a dense MatrixTable? Or any suggestion to adapt the current code?
Thanks in advance for your help!

**Comment by ch-kr** [comment]
sex inference on dense data exists in TGG methods https://github.com/broadinstitute/tgg_methods/blob/master/tgg/seqr_scripts/sex_check.py
