### ISSUE TITLE
Generic liftover

### ISSUE THREAD

**Issue by lfrancioli** [broadinstitute/gnomad_methods#190]
Right now much of the code in utils.liftover is specific (or has specific options) for gnomad; specific parts should be moved to `gnomad_qc.v2` and all there should be generic.

I also think that checkpointing should be taken out of e.g. `lift_data` since it may not be desirable in all situations (e.g very small table)

Finally, docstring needs work, e.g. `:param rg: Reference genome` --> is this the old or new reference?

**Comment by lfrancioli** [comment]
Something like this may be generally useful:

```
def liftover_expr(
        locus: hl.expr.LocusExpression,
        alleles: hl.expr.ArrayExpression,
        destination_ref: hl.ReferenceGenome
) -> hl.expr.StructExpression:

    lifted_over_locus=hl.liftover(locus, destination_ref, include_strand=True)
    lifted_over_alleles=alleles.map(
        lambda a: hl.if_else(lifted_over_locus.is_negative_strand,  hl.reverse_complement(a), a)
    )
    return hl.struct(
        locus=lifted_over_locus.result,
        alleles=lifted_over_alleles
    )
```

Also, something else to consider:
```
        bad_liftover=(
            hl.is_missing(cmg_ht.locus1) |
            hl.is_missing(cmg_ht.locus2) |
            (cmg_ht.locus1.sequence_context() != cmg_ht.alleles1[0][0]) |
            (cmg_ht.locus2.sequence_context() != cmg_ht.alleles2[0][0])
        )
```

**Comment by nawatts** [comment]
Related to #162

**Comment by ch-kr** [comment]
Finally opened a PR for this: https://github.com/broadinstitute/gnomad_methods/pull/246

**Comment by nawatts** [comment]
Now that #246 is merged, is this issue resolved?

**Comment by lfrancioli** [comment]
Yup!
