### ISSUE TITLE
Use local copy of VEP configuration

### ISSUE THREAD

**Issue by nawatts** [broadinstitute/gnomad_methods#226]
Currently, VEP configuration is downloaded from Hail's US bucket.
https://github.com/broadinstitute/gnomad_methods/blob/2090cbb6672474cdfbfc6ab0a8fb54275fd03499/gnomad/utils/vep.py#L65-L74

This bucket is requestor pays, so reading from it requires that either `--requester-pays-allow-all` or `--requester-pays-allow-buckets hail-us-vep` is specified when starting the cluster. If someone isn't aware of that, it's easy to start a cluster (which takes a fair amount of time with VEP) that can't run the gnomAD VEP utilities.

`hailctl dataproc`'s VEP init scripts download these configuration files and link them to `/vep_data/vep-gcloud.json`. If VEP configuration was loaded from the local copy downloaded by the init scripts instead of the `hail-us-vep` bucket, then the requestor pays arguments would not be necessary. 

https://github.com/hail-is/hail/blob/498f73704368ea548dfcd4acc469c6fbcd61f83a/hail/python/hailtop/hailctl/dataproc/resources/vep-GRCh37.sh#L26-L28

https://github.com/hail-is/hail/blob/498f73704368ea548dfcd4acc469c6fbcd61f83a/hail/python/hailtop/hailctl/dataproc/resources/vep-GRCh38.sh#L26-L28

**Comment by lfrancioli** [comment]
Makes total sense to me.
