### ISSUE TITLE
How to select subset sites

### ISSUE THREAD

**Issue by fzc1997** [broadinstitute/gnomad_methods#239]
I have a list of sites identified by their genomic coordinate, how can I select these sites in your hail table. I want to know the syntax.

**Comment by nawatts** [comment]
Hi @fzc1997,

To filter the Hail table to a single site:
```python
table = gnomad.public_release("exomes").ht()
table = table.filter(table.locus == hl.Locus("1", 55505512, reference_genome="GRCh37"))
```

To filter the Hail table to all sites in an interval:
```python
table = gnomad.public_release("exomes").ht()
table = hl.filter_intervals(table, [hl.parse_locus_interval("1:55505221-55530525", reference_genome="GRCh37")])
```

Another method is shown in https://hail.is/docs/0.2/guides/genetics.html#filter-loci-by-a-list-of-locus-intervals
