### ISSUE TITLE
Publish documentation for latest release

### ISSUE THREAD

**Issue by nawatts** [broadinstitute/gnomad_methods#248]
Currently, we publish documentation on every commit to master, so https://broadinstitute.github.io/gnomad_methods/ contains documentation for the latest development version. However, users are likely using the last PyPI release, which may lag behind development. We should possibly publish documentation only on releases or publish both a stable and development version of documentation.

**Comment by nawatts** [comment]
An example of confusion caused by this: https://discuss.hail.is/t/cannot-import-gnomad-utils-annotations-sor-from-sb/1920.

**Comment by gtiao** [comment]
Not sure if this is still relevant -- needs refinement

**Comment by ch-kr** [comment]
we now create pypi releases after each gnomAD version release -- can open a new ticket if this becomes an issue again
