### ISSUE TITLE
Update resource paths to new Google/AWS/Azure public hosted data

### ISSUE THREAD

**Issue by gtiao** [broadinstitute/gnomad_methods#255]
Since we'll end up with 3 versions (one on each of the major cloud providers) for each public file, we'll need to implement a new structure for specifying which cloud version to use

**Comment by nawatts** [comment]
#373 added support for reading resources from the Google Cloud Public Datasets bucket.

See https://github.com/broadinstitute/gnomad_methods/pull/373/commits/f44ae96abcaf958800f41746efebae5703fcc0a5 for an example of how to add support for AWS and Azure.

**Comment by nawatts** [comment]
It's not immediately clear what the URL scheme for files on AWS would be.

https://hadoop.apache.org/docs/stable/hadoop-aws/tools/hadoop-aws/index.html and https://spark.apache.org/docs/3.1.1/cloud-integration.html#recommended-settings-for-writing-to-object-stores suggest `s3a://`.

https://hadoop.apache.org/docs/stable/hadoop-aws/tools/hadoop-aws/index.html#Other_S3_Connectors mentions an `s3://` client from Amazon EMR.

**Comment by jkgoodrich** [comment]
Need to update gnomad_methods resource code for AWS and Azure: https://github.com/broadinstitute/gnomad_methods/blob/master/gnomad/resources/resource_utils.py
