### ISSUE TITLE
Update gnomAD resources to reflect free Google Cloud-hosted paths

### ISSUE THREAD

**Issue by gtiao** [broadinstitute/gnomad_methods#264]
Prefixes should change from `gs://gnomad-public/` or `gs://gnomad-public-requester-pays/` to `gs://gcp-public-data--gnomad`

**Comment by nawatts** [comment]
Along with this, we should also remove the `gnomad-public-requester-pays` bucket from the [getting started](https://github.com/broadinstitute/gnomad_methods/blob/master/docs/getting_started.rst) and [VEP](https://github.com/broadinstitute/gnomad_methods/blob/master/docs/examples/vep.rst) docs.

**Comment by nawatts** [comment]
#373 added support for reading resources from the Google Cloud Public Datasets bucket. Do we want to make that the default?

**Comment by gtiao** [comment]
Need to check that all recent, most updated files are synced to public GCP bucket, and then can proceed.

Nick notes that would be better/ideal to have entire bucket synced to GCP public bucket.

**Comment by nawatts** [comment]
A quick check revealed that the public GCP bucket's `resources` directory only contains the VEP 85 and 95 context Hail Tables.

So none of the reference data resources are available from that bucket.

**Comment by nawatts** [comment]
We could still change the default source to the GCP bucket, if we assume that most users will be interested in the gnomAD resources vs the reference data resources.

#388 will also help with this by adding a more informative error message when a resource is not available from the selected source.
