### ISSUE TITLE
Avoid hyphenated field names in VCF export

### ISSUE THREAD

**Issue by nawatts** [broadinstitute/gnomad_methods#272]
Hyphenated info keys are incompatible with `bcftools query` format (samtools/bcftools#1335).

Hyphenated info keys are also not allowed in [version 4.3 of the VCF specification](https://samtools.github.io/hts-specs/VCFv4.3.pdf) (item 8 of section 1.6.1). (CurrentgnomAD VCFs are version 4.2)

VCF export scripts should validate field names against the regular expression in the VCF spec.

**Comment by gtiao** [comment]
Issue has been logged in gnomad_qc repo: https://github.com/broadinstitute/gnomad_qc/issues/160

Closing this issue as a duplicate issue.
