### ISSUE TITLE
StructExpression instance has no field 'gq_stats' in compute_stratified_sample_qc

### ISSUE THREAD

**Issue by vladsaveliev** [broadinstitute/gnomad_methods#274]
Thank you so much for making gnomad_methods public and releasing a python package! It's super helpful and would tremendously help setting up a QC pipeline for our own datasets.

I was wondering about the usage of `compute_stratified_sample_qc` method. It starts with subsetting the matrix table entry fields to the GT field here, leaving out the GQ and DP fields:
https://github.com/broadinstitute/gnomad_methods/blob/ef0fbf3b78ee675b5a94c0673fc28bf6a0960e9c/gnomad/sample_qc/filtering.py#L202-L205

However, a bit down that function, `sample_qc` is called:
https://github.com/broadinstitute/gnomad_methods/blob/ef0fbf3b78ee675b5a94c0673fc28bf6a0960e9c/gnomad/sample_qc/filtering.py#L208-L209

Which [uses GQ and DP](https://github.com/hail-is/hail/blob/306023feb427c6197fde94552ecff7c61b816057/hail/python/hail/methods/qc.py#L112-L116) to calculate `dp_stats` and `gq_stats` correspondingly, that are required by `merge_sample_qc_expr` called a few more lines down:
https://github.com/broadinstitute/gnomad_methods/blob/ef0fbf3b78ee675b5a94c0673fc28bf6a0960e9c/gnomad/sample_qc/filtering.py#L226-L228

Because GQ and DP are not kept, I'm getting this error at this line:https://github.com/broadinstitute/gnomad_methods/blob/ef0fbf3b78ee675b5a94c0673fc28bf6a0960e9c/gnomad/sample_qc/filtering.py#L313

```
KeyError: "StructExpression instance has no field 'gq_stats'\n    Hint: use 'describe()' to show the names of all data fields."
```

Wondering if I'm missing something? Should `DP` and `GQ` be added into `mt.select_entries` in `compute_stratified_sample_qc`, as well as into [`compute_sample_qc` at gnomad_qc](https://github.com/broadinstitute/gnomad_qc/blob/d63c00f9fd3e38b9c2606c61ac868713faee5d34/gnomad_qc/v3/sample_qc/sample_qc.py#L54)?

**Comment by vladsaveliev** [comment]
Huh, after installing the latest codebase from git and retrying, I'm not getting the error :)

**Comment by nawatts** [comment]
Hi @vladsaveliev,

There have been a lot of changes recently in the lead up to releasing gnomAD v3 which are not yet reflected in the code on PyPI (which was last updated in July). We're currently working on reviewing and merging several PRs in this repo and [gnomad_qc](https://github.com/broadinstitute/gnomad_qc) and will cut a new PyPI release once that is finished.

**Comment by vladsaveliev** [comment]
Oh, nice to hear that :) Thanks for your work!
