### ISSUE TITLE
Reconcile v3.1 changes to common code functions within gnomad_qc/v3

### ISSUE THREAD

**Issue by mike-w-wilson** [broadinstitute/gnomad_methods#276]
Functions to be reconciled:
ht_to_vcf_mt
make_hist_dict
make_info_dict
make_vcf_filter_dict
add_as_info_dict
make_label_combos
remove_fields_from_globals
build_export_reference()

**Comment by jkgoodrich** [comment]
@mike-w-wilson what is the status of these?

**Comment by jkgoodrich** [comment]
~~ht_to_vcf_mt~~ -We have changed this to be [`adjust_vcf_incompatible_types`](https://github.com/broadinstitute/gnomad_methods/blob/98a41fd30210fdb715b4db77b6f0217ef11ea8e3/gnomad/utils/vcf.py#L326)
~~make_hist_dict~~ -In gnomad [vcf.py](https://github.com/broadinstitute/gnomad_methods/blob/98a41fd30210fdb715b4db77b6f0217ef11ea8e3/gnomad/utils/vcf.py#L824) and works with new v3.1 VCF generation script
~~make_info_dict~~ -In gnomad [vcf.py](https://github.com/broadinstitute/gnomad_methods/blob/98a41fd30210fdb715b4db77b6f0217ef11ea8e3/gnomad/utils/vcf.py#L525) and works with new v3.1 VCF generation  script
~~make_vcf_filter_dict~~ -In gnomad [vcf.py](https://github.com/broadinstitute/gnomad_methods/blob/98a41fd30210fdb715b4db77b6f0217ef11ea8e3/gnomad/utils/vcf.py#L723) and works with new v3.1 VCF generation  script
~~add_as_info_dict~~ -In gnomad [vcf.py](https://github.com/broadinstitute/gnomad_methods/blob/98a41fd30210fdb715b4db77b6f0217ef11ea8e3/gnomad/utils/vcf.py#L688) and works with new v3.1 VCF generation  script
~~make_label_combos~~ -In gnomad [vcf.py](https://github.com/broadinstitute/gnomad_methods/blob/98a41fd30210fdb715b4db77b6f0217ef11ea8e3/gnomad/utils/vcf.py#L395). Updated with necessary changes for v3.1 QC. Not used within `gnomad_qc` but functions in `gnomad_methods` that use this have also been updated for proper used in v3.1 QC.
~~remove_fields_from_globals~~ - now named [`remove_fields_from_constant`](https://github.com/broadinstitute/gnomad_methods/blob/3536f87e249f0804f6762facce468597a9c441c6/gnomad/utils/filtering.py#L346) and in gnomad_methods

Everything in v3.1 is reconciled with these changes in #191
