### ISSUE TITLE
Update clinvar VCF to lateset release

### ISSUE THREAD

**Issue by mike-w-wilson** [broadinstitute/gnomad_methods#277]
ClinVar releases a new VCF every month. gnomAD v3.1 used the same VCF/HT as v3 which dates to Sept 2019. The new ClinVar resource should be added to the reference data module as a new version in the clinvar VersionedTableResource.

**Comment by jkgoodrich** [comment]
Do we have a way to automatically update this each month, or do we only update when someone needs the newer version?

**Comment by jkgoodrich** [comment]
OK, that makes sense, then this doesn't impact v3.1 release at all really. I don't think those plots will change much and we used other metrics for evaluation as well.

**Comment by jkgoodrich** [comment]
Closing, this is not relevant for the gnomAD releases
