### ISSUE TITLE
Extra sanity checks on all release files

### ISSUE THREAD

**Issue by jkgoodrich** [broadinstitute/gnomad_methods#338]

**Comment by jkgoodrich** [comment]
I am allotting time for a full manual inspection of all release files to go along with the automated sanity checks that we have. It would be good to open files up to a larger number of individuals to look over the release files before an official release in case there are problems that are missed by our automated sanity checks (possibly because the problem hasn't come up before).

**Comment by ch-kr** [comment]
closing this -- we are hoping to update how we run validity checks in the future, and we're also trying to buffer time for internal QA prior to releases to try to have more eyes on release data (via demo browser) prior to public release
