### ISSUE TITLE
"r" vs "v" in gnomAD resources versions

### ISSUE THREAD

**Issue by nawatts** [broadinstitute/gnomad_methods#350]
Some versions of resources are named "r<version>" and some "v<version>". Going forward, "v" is the preference. However, some code still assumes "r".

For example,
https://github.com/broadinstitute/gnomad_methods/blob/212c3761ffeb4f925d3b44361bf8085a417a15d3/gnomad/resources/grch37/gnomad.py#L61-L69

**Comment by nawatts** [comment]
We currently create these VersionedTableResource instances in the `public_release`, `coverage`, etc. functions. However, there are only a few gnomAD versions, so is there much value in having

```python
VersionedTableResource(
    current_release,
    {
        release: TableResource(path=_public_release_ht_path(data_type, release))
        for release in releases
    },
)
```

instead of

```python
VersionedTableResource(
    current_release,
    {
        "2.1.1": TableResource(path="..."),
        "2.1": TableResource(path="...")
    },
)
```

The latter has no assumption that the URLs for all versions follow the same pattern.

**Comment by gtiao** [comment]
That would help things, but I guess the question is if we're moving towards
more frequent releases in the future, will that way of listing filepaths
end up ultimately being annoying/highly redundant?

**Comment by nawatts** [comment]
Do we expect the frequency of releases to be more than a few per year?

I also like the explicit list of versions since it avoids having to add special cases like no coverage for v2.1.1 or liftover only for v2.1. Even with only two versions in the GRCh37 resources file, such special cases [resulted in bugs](#352).

**Comment by gtiao** [comment]
No, I don't -- not anytime soon, at least! @Julia Goodrich
***@***.***> what do you think?
