### ISSUE TITLE
Improve changelog updates

### ISSUE THREAD

**Issue by nawatts** [broadinstitute/gnomad_methods#355]
The current process for updating the changelog has some issues.

* Updates in multiple PRs cause merge conflicts.
* Adding links to PRs requires another commit after opening a PR.

It works ok with a low volume of PRs, but merge conflicts become more of a problem with more PRs.

One alternative would be to update the changelog only on releases. However,
* PyPI releases are so infrequent that attempting to gather a list of changes and create a changelog at release time would be difficult.
* We use the latest git revision instead of the latest PyPI release in gnomad_qc so it's useful to have the changelog always up to date instead of only updated on PyPI releases.

More frequent releases could resolve those issues.

Another option would be storing the changelog outside of the repository content. https://github.com/marketplace/actions/release-drafter or something similar looks promising. Each release has its changelog and a draft release has a changelog for the latest development version. The changelog file could also be updated from the release notes on each release.

**Comment by nawatts** [comment]
Perhaps the easiest thing to do is add changelog entries just before merging instead of when creating the PR.

**Comment by jkgoodrich** [comment]
Agree that is a fine way to do it, but I do often forget, so I guess it's good to also encourage reviewers to hold on an approval without the changelog addition when it is needed so there are at least two checks on it.

**Comment by nawatts** [comment]
Good point. We could also add a PR check that blocks merging unless the PR modifies the changelog or has something like "Changelog not needed" in the description or a comment.
