### ISSUE TITLE
Empty `gs://gnomad-public`

### ISSUE THREAD

**Issue by vladsaveliev** [broadinstitute/gnomad_methods#400]
The code uses a set of reference files located under `gs://gnomad-public`, like `gs://gnomad-public/resources/grch38/telomeres_and_centromeres/hg38.telomeresAndMergedCentromeres.ht`. But at the moment, that bucket appears to be empty. Were files relocated anywhere by any chance?

**Comment by nawatts** [comment]
Hi @vladsaveliev 

All the files in `gs://gnomad-public` were recently relocated to `gs://gnomad-public-requester-pays`.

https://gnomad.broadinstitute.org/news/2021-08-gnomad-hosted-public-files-moved-to-requester-pays-bucket/

**Comment by vladsaveliev** [comment]
Oh, fantastic, thanks for the response!
