### ISSUE TITLE
Sex plodiy cutoffs: lower cutoff for single Y?

### ISSUE THREAD

**Issue by vladsaveliev** [broadinstitute/gnomad_methods#428]
As the docstring says, the first value of `y_ploidy_cutoffs` should be "lower cutoff for single Y". 
Should it be changed in the code as follows?

```diff
- sex_stats["xx"].y.mean
-                + (normal_ploidy_cutoff * sex_stats["xx"].y.stdev),
+ sex_stats["xy"].y.mean
+                - (normal_ploidy_cutoff * sex_stats["xy"].y.stdev),
```

https://github.com/broadinstitute/gnomad_methods/blob/35066ffc01d63ac2d7b20e069ea6703013ae9da7/gnomad/sample_qc/sex.py#L117-L118

**Comment by ch-kr** [comment]
Great question! The reason this line uses `sex_stats["xx"].y.mean` is to correctly infer all chromosome Y (chrY) karyotypes, including karyotypes where a sample has no Y chromosome. This value is used twice: https://github.com/broadinstitute/gnomad_methods/blob/master/gnomad/sample_qc/sex.py#L164 and https://github.com/broadinstitute/gnomad_methods/blob/master/gnomad/sample_qc/sex.py#L167. 

* Line 164 checks the scenario when a sample's chrY ploidy is less than `sex_stats["xx"].y.mean`. This is to check whether a sample does not have a single Y chromosome (catching X, XX, XXX karyotypes, for example).
* Line 167 uses `sex_stats["xx"].y.mean` as the lower chrY ploidy cutoff (and this part of the case statement checks for whether a sample has a single Y chromosome).

Also, as a quick note, the ploidy cutoffs from this function should be double checked and tweaked where necessary; this function only provides a guideline for what the cutoffs could be.

Would it be helpful if I added some of these notes into the docstring for `get_ploidy_cutoffs`?

**Comment by ldgauthier** [comment]
I understand why the poly-T in the reference is so "attractive", but I don't understand why the mates of those reads don't disqualify them from that locus.  I wonder if DragMap has different logic regarding mapping of mates.  I'm very concerned about this behavior.  Can you get more info on a few of the mates?  I believe you can do it from the read details in IGV.

In most regions, DP should correlate really well with GQ, so I would expect 712X to be higher than GQ20, and it would be in a different block from the no coverage GQ0s.  I would have suggested MIN_DP, expect the MIN_DP for GQ0 will probably be zero more often than not.  We can do pretty reliable Y ploidy inference from exomes, so restricting to some high quality and/or well behaved intervals will probably still yield enough data.  In the gs://gcp-public-data--broad-references (in hg38/v0/ or something like that) there should be an interval_list called `exome_evaluation_regions`, which would be a good place to start for high quality intervals.

**Comment by vladsaveliev** [comment]
I looked at a bunched of reads mapping to that locus, and they all have a mate mapping somewhere else in the genome (different every time) with a higher MQ, and also often a supplementary alignment mapping somewhere else again (differently from the mate.)

Made screenshots of 3 arbitrary reads:

Read:

```
A00488:117:HVTVGDSXY:1:2606:1099:33051	113	chrY	15896766	0	3S31M1D29M87S	chr20	61410542	0	TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTGTTTTTTTTTTGTTTTTTTTTTTTATTTTGTTTTTTTTTTTTGTTTTTGTTTGGATGTTTGTATTGTTGGTTTTTAGTGTTGGATTTTTTGTAGATGTATGTTTTTGTAGTTTGATT	???????+??????+???+???????+??+???+????++????+?????+?+?+??+???++?+???+?++?+????????????????????5???????????????????????+???+???????'?5?+??+?????+??????	SA:Z:chr13,104356596,+,65H37M48H,0,1;	MC:Z:150M	MQ:i:19	AS:i:48	XS:i:46	mc:i:61410691	ms:i:4764	MD:Z:31^T23T5	NM:i:2	RG:Z:HVTVGDSXY.1-2-3-4.210316_FD09252752
```

His mate:

```
A00488:117:HVTVGDSXY:1:2606:1099:33051	177	chr20	61410542	19	150M	chrY	15896766	0	TACATTCCACTCACTGGTCCATCTATCCATCCATTCATCCATCTGTCAATCATCCATCTACACATCCCTCCATCTTCCATTCCTCCCACTGGTCCATCCATCCATCCATCCATCCATCCTCTCACTTGTTAGTCCATTGACCTGTCCATC	?+??++??+?+?+?+++??+???????????+???+????+?+?+????+????????5????????????????????????????+?+?5??????????????????????????????????????????????????????????	MC:Z:3S31M1D29M87S	MQ:i:0	AS:i:140	XS:i:118	mc:i:15896913	ms:i:4360	MD:Z:1C6T141	NM:i:2	RG:Z:HVTVGDSXY.1-2-3-4.210316_FD09252752
```


<img width="1440" alt="Screen Shot 2022-01-12 at 4 59 00 pm" src="https://user-images.githubusercontent.com/1575412/149072295-d649d6bf-e451-4775-9939-8d9db26ce212.png">


Read:

```
A00488:117:HVTVGDSXY:1:1315:24108:27211	177	chrY	15896766	2	59S60M31S	chr11	77041117	0	GGGGGGTTGTGTGTTGGTGGGGTTTTTTTTTTTTTGTTTTTGGGGGGTTTGTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTGTTTTTGTTTTTTTTTTTCTTTTTTTTTTTTTTTTTTTTTTTTTTAAAAAAAAAAAAAACCCCCCCT	+?+?++++++???+++5+++++??+??????????++?++5+??+++++++?++?+??+??+???????????????+??++++++++?++??++?++???++??+?+++???+?++?+??????++'+???+???5??55+????????	SA:Z:chr12,50924517,+,9H39M102H,0,0;	MC:Z:150M	MQ:i:60	AS:i:50	XS:i:45	mc:i:77041266	ms:i:5526	MD:Z:24T17G17	NM:i:2	RG:Z:HVTVGDSXY.1-2-3-4.210316_FD09252752
```

Mate:

```
A00488:117:HVTVGDSXY:1:1315:24108:27211	113	chr11	77041117	60	150M	chrY	15896766	0	CAGCGCCCCCTGCCATGTGCCTACAAATGTCAGTTGTGATTTCCACTGTTTACAAGTGAGTGGAGCTGGAGCTGGGCTGACAGTGTCAGGTGGATCCCGCTTCCCCCTCCCCCAAGAAGTCAGCCAACACGCAGCTGAGGCGCATGTGGT	??????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????	MC:Z:59S60M31S	MQ:i:2	AS:i:145	XS:i:20	mc:i:32866959	ms:i:2626	MD:Z:84A65	NM:i:1	RG:Z:HVTVGDSXY.1-2-3-4.210316_FD09252752
```

<img width="1440" alt="Screen Shot 2022-01-12 at 5 07 09 pm" src="https://user-images.githubusercontent.com/1575412/149073970-7d8d8b96-1508-48fb-b8d5-311bd293ebe8.png">



Read:

```
A00488:117:HVTVGDSXY:4:1501:9281:3443	145	chrY	15896766	0	25S61M64S	chrX	114564847	0	TTTACTTTTTTCTTTTTTTTCTTCTTTTTTTTTTTTTTTTTTATTTTTATTTTTTATTTTTTTTTTTTTTTTTTTTTTTTTTTTTGTTTTTCTTTTTTCGTTTTTGCGTTCGTCTGCCCCCTCCTCCCCCCCCCCCCCCCCCCCCCCCCC	??'++?++++++?++++++++?++++?+?+++++++?++++'+++++5+???++?+?+++?+++?+++???+?+++???++?+??+++++++++++++%+++++55%+?+%++++5++++++++++++++++++++++????????????	SA:Z:chr5,112769033,-,6H36M108H,0,0;	MC:Z:151M	MQ:i:60	AS:i:41	XS:i:40	mc:i:114564847	ms:i:5563	MD:Z:17T5T6G11G18	NM:i:4	RG:Z:HVTVGDSXY.1-2-3-4.210316_FD09252752
```

Mate:

```
A00488:117:HVTVGDSXY:4:1501:9281:3443	97	chrX	114564847	60	151M	chrY	15896766	0	TTAACCGACACACAGTCAGATTTTAAGCAGTAACCATTTGAAAGGTCACTTTAGAAGCAATGTGGAGAAGTAACTTGAAGAGGTGGGACTGGAAGCAAGAAGAAGTGCTTGGACACTAAAGATGTAATATGCCAGGTGAAGGAGAACATGT	??????5????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????	MC:Z:25S61M64S	MQ:i:0	AS:i:151	XS:i:19	mc:i:172218716	ms:i:1216	MD:Z:151	NM:i:0	RG:Z:HVTVGDSXY.1-2-3-4.210316_FD09252752
```

<img width="1440" alt="Screen Shot 2022-01-12 at 5 13 55 pm" src="https://user-images.githubusercontent.com/1575412/149073975-c3de07af-55f9-41ae-b820-d34e0d7462a4.png">

----

In BWA, actually, the region looks very similar: 

<img width="1034" alt="Screen Shot 2022-01-12 at 5 39 14 pm" src="https://user-images.githubusercontent.com/1575412/149078242-d14d962d-bda1-4a1f-a857-2d08b7e58e78.png">

The GVCFs records resulting from these alignments, however, are different (still low-GQ block, but called variants split it into 6):

```
bcftools view -H -r chrY:15896761-15896857 DRAGMAP.g.vcf.gz
chrY	15886743	.	A	<NON_REF>	.	DRAGENHardQUAL	END=16027941	GT:DP:GQ:MIN_DP:PL	0/0:697:0:0:0,0,0

bcftools view -H -r chrY:15896761-15896857 BWAMEM.g.vcf.gz 
chrY	15883027	.	A	<NON_REF>	.	.	END=15896771	GT:DP:GQ:MIN_DP:PL	0/0:6:0:0:0,0,0
chrY	15896772	.	T	A,<NON_REF>	0.01	.	.	GT	./.
chrY	15896773	.	T	G,<NON_REF>	0.01	.	.	GT	./.
chrY	15896774	.	T	<NON_REF>	.	.	END=15896774	GT:DP:GQ:MIN_DP:PL	0/0:0:0:0:0,0,0
chrY	15896775	.	T	G,<NON_REF>	0.01	.	.	GT	./.
chrY	15896776	.	T	<NON_REF>	.	.	END=16027941	GT:DP:GQ:MIN_DP:PL	0/0:1:0:0:0,0,0
```

**Comment by vladsaveliev** [comment]
> In most regions, DP should correlate really well with GQ

Shouldn't GQ also depend on MQ of reads? DP would include low-MQ reads:

```
##FORMAT=<ID=DP,Number=1,Type=Integer,Description="Approximate read depth (reads with MQ=255 or with bad mates are filtered)">
```

Resulting in a high DP; However GQ would remain small (as in this region).

> We can do pretty reliable Y ploidy inference from exomes, so restricting to some high quality and/or well behaved intervals will probably still yield enough data

Thanks!! 

I worked around this issue by removing regions with a very high coverage (10x times the normalization contig coverage):

```
mt = mt.filter_entries(mt.DP < 10 * mt.chr20_mean_dp)
```

And it works very well. However, white/blacklisting regions will be a better approach, as it wouldn't require modifying the gnomad methods codebase.

**Comment by ldgauthier** [comment]
The BWA-derived GVCF makes more sense to me.  Yes, there are GQ0 blocks and calls, but the depth on the ref blocks is very low, which is what I would expect for chrY on a female.

We're seen a lot of discrepancies between DP in comparing DRAGEN with GATK (4.1 and onwards, I believe).  Most of these seem to revolve around differences in how low mapping qualities are treated, so I think using regions of "high confidence" would be a robust way to move forward.

**Comment by vladsaveliev** [comment]
Thanks a lot for your help!
