### ISSUE TITLE
Update test_resource_utils.py to eliminate the requester-pays resource testing

### ISSUE THREAD

**Issue by gtiao** [broadinstitute/gnomad_methods#438]
I'm planning to archive the gs://gnomad-public-requester-pays data, so it probably doesn't make sense to maintain functions that call data from that bucket:

https://github.com/broadinstitute/gnomad_methods/blob/e625c03b4f5e4d60b1b7c15402eeeab7a92ea3ea/tests/resources/test_resource_utils.py

**Comment by ch-kr** [comment]
need to check whether this is still relevant

**Comment by ch-kr** [comment]
closing since it has been a year -- we can open a new ticket if needed
