### ISSUE TITLE
Test running pre-processing steps of existing constraint pipeline

### ISSUE THREAD

**Issue by ch-kr** [broadinstitute/gnomad_methods#459]

**Comment by jkgoodrich** [comment]
Completed, the code and tables have been looked over. Avery will add the path to the jupyter notebook

**Comment by averywpx** [comment]
path to the testing code: gs://gnomad-avery/constraint/testing_constraint_code.ipynb

**Comment by klaricch** [comment]
Avery will add docstring and submit PR

**Comment by averywpx** [comment]
The repo haven't been added. Here is the link to PR: https://github.com/macarthur-lab/gnomad_lof/pull/7

**Comment by averywpx** [comment]
Path to regenerated exome table: gs://gnomad-avery/constraint/model/exomes_processed.ht
Path to regenerated genome table: gs://gnomad-avery/constraint/model/genomes_processed.ht
