### ISSUE TITLE
KING and pc-relate comparison on v4 test dataset

### ISSUE THREAD

**Issue by ch-kr** [broadinstitute/gnomad_methods#464]
Leo from Daniel's team is working on comparing these two tools on the v4 test datset

**Comment by ch-kr** [comment]
Leo has run KING and pc-relate on v4 test dataset. KING is pulling out the same related UKB samples as before, but pc-relate results look strange.

Next steps: ask Leo to run KING on HGDP/TGP dataset and compare to relatedness results in public metadata ht

**Comment by ch-kr** [comment]
Slides from Leo: https://docs.google.com/presentation/d/1rE590d8-6AoIY4jkRAcnsbgD_A8bouMzDFG-UM1kj3c/edit?usp=sharing

next steps: Konrad wants to look into samples with KING values of 0.25 and pc-relate values of 0.1

**Comment by gtiao** [comment]
Leo will run comparison on v3.1

**Comment by ch-kr** [comment]
Samples with KING kinship ~0.25 and pc-relate kinship ~0.1:
https://atgu.slack.com/archives/CRA2TKTV0/p1657722329316969?thread_ts=1656083070.858349&cid=CRA2TKTV0
![image.png](https://images.zenhubusercontent.com/5fc68b5811d994b942a7916b/9cd21848-924a-4f3d-905a-31838c3c51e7)

Dan King's comments: https://atgu.slack.com/archives/CRA2TKTV0/p1657724973926609?thread_ts=1656083070.858349&cid=CRA2TKTV0 and https://atgu.slack.com/archives/CRA2TKTV0/p1657725090071819?thread_ts=1656083070.858349&cid=CRA2TKTV0
