### ISSUE TITLE
Is there any command can be used to extract de novo mutations

### ISSUE THREAD

**Issue by xsun1229** [broadinstitute/gnomad_methods#518]
Hi,

I am trying to extract de novo mutations from the gnomAD dataset and I was wondering if there is any command or tool that can be used for this purpose. I have downloaded the VCF files from the gnomAD website, but I am not sure if the VCF files contain de novo annotations or how to filter the data to identify de novo mutations.

I would greatly appreciate any guidance or advice.

Thank you in advance for your help!
Best regards,
Miley

**Comment by ch-kr** [comment]
Hi,

Thanks for reaching out to us. In general, questions or feedback about the gnomAD dataset should be directed to [gnomad@broadinstitute.org](mailto:gnomad@broadinstitute.org); GitHub issues should be limited to code-related questions or feedback.

We do not release de novo annotations. This page may be helpful in describing our available annotations: https://gnomad.broadinstitute.org/help/v3-ht-annotations.

You could try searching for de novo variants in our [HGDP +1 KG subset](https://gnomad.broadinstitute.org/downloads#v3-hgdp-1kg), as the MatrixTables and VCFs associated with this subset contain individual-level data. One tool that might be helpful is Hail's `de_novo` [method](https://hail.is/docs/0.2/methods/genetics.html#hail.methods.de_novo).
