### ISSUE TITLE
assign_population_pcs() throws InvalidIndexError when input pop_pca_scores is a Dataframe

### ISSUE THREAD

**Issue by LindoNkambule** [broadinstitute/gnomad_methods#538]
Hi gnomAD team,

I was trying to use the [assign_population_pcs()](https://github.com/broadinstitute/gnomad_methods/blob/246d5b6d2d1453ac373433fb38f892c5d0b581f0/gnomad/sample_qc/ancestry.py#L120) function as follows and got a `InvalidIndexError: Reindexing only valid with uniquely valued Index objects` error:

```
from gnomad.sample_qc.ancestry import assign_population_pcs
gnomad_infered = assign_population_pcs(scores_df_gnomad, colnames, known_col='SuperPop')
```

`scores_df_gnomad` is a Dataframe with the following columns: `s,PC1,...,PC20,SuperPop`. 
`colnames` is the following list: `["PC1", "PC2", ..., "PC20"]`

The error is from [line 263](https://github.com/broadinstitute/gnomad_methods/blob/5388ba870959e5ab790f86daad4294b8017f3065/gnomad/sample_qc/ancestry.py#L263) and updating the code from
`pop_pc_pd = pd.concat([pop_pc_pd, probs], axis=1)`
to
`pop_pc_pd = pd.concat([pop_pc_pd.reset_index(drop=True), probs.reset_index(drop=True)], axis=1)` fixed the issue.

**Comment by jkgoodrich** [comment]
Thank you Lindo! Your suggested fix was added in [#588](https://app.zenhub.com/workspaces/gnomad-5f4d127ea61afc001d6be50b/issues/gh/broadinstitute/gnomad_methods/558)
