### ISSUE TITLE
accessing whole genome vcf for Europeans(Finish and non Finish)

### ISSUE THREAD

**Issue by smhaider** [broadinstitute/gnomad_methods#562]
Hello everyone,

Thank you so much for such a nice resource,  I have a query regarding the availability of whole genome VCF data exclusively for Europeans, including both Finnish and non-Finnish populations. Specifically, I am interested in obtaining age_bin information for each SNP, limited to the European population. I would greatly appreciate any assistance or guidance regarding this matter.

Kind Regards,
Haider

**Comment by ch-kr** [comment]
Hi,

Thanks for reaching out to us. In general, questions or feedback about the gnomAD dataset should be directed to [gnomad@broadinstitute.org](mailto:gnomad@broadinstitute.org); GitHub issues should be limited to code-related questions or feedback.

We only calculate age distributions across all samples in gnomAD. For more information, please see our help [page](https://gnomad.broadinstitute.org/help/what-is-the-age-distribution-in-gnomad). Another resource that may be of interest is the [UK Biobank](https://www.ukbiobank.ac.uk/).
