### ISSUE TITLE
Variant allele frequency versus population frequency

### ISSUE THREAD

**Issue by MaryGoAround** [broadinstitute/gnomad_methods#664]
Hi

Can I use gnomAD non-cancer data as a control instead of using gnomAD controls/biobank data to compare with my cancer data?

**Comment by ch-kr** [comment]
Hi,

Thanks for reaching out to us. In general, questions or feedback about the gnomAD dataset should be directed to our [forum](https://discuss.gnomad.broadinstitute.org/); GitHub issues should be limited to code-related questions or feedback.
