### ISSUE TITLE
Default Variant Filtering Browser vs. Hail Table

### ISSUE THREAD

**Issue by nchambwe** [broadinstitute/gnomad_methods#97]
We are studying three gene families of interest so we would like to examine the landscape of population genetic variation in members of these families. Our gene list has 50 genes+ and so I wanted to use a programmatic approach to query gnomaD for the relevant variants of interest.  
To that end, I am learning and exploring the data using the Hail tables and have downloaded the latest release gnomaD table (v 2.1.1) from the [downloads page](https://gnomad.broadinstitute.org/downloads).

A curious observation: 
If I use the gnomad Brower for the query gene: FANCA, the number of variants returned using this approach is 4854. However, if I follow many of the suggested filters from the release blog from [the macarthur lab blog](https://macarthurlab.org/2018/10/17/gnomad-v2-1/#more-1203) and filter the Hail Tables with the filters described below then I arrive at a very different variant count compared to the direct browser download. 

FANCA Variant set: n=4854 (Filters PASS)
Using the 'Source' column, I can see the variant breakdown is the following:
exomes only: 3331
genomes only: 572
shared: 951
FANCA Variant set: (Hail Table Filtering Approach)
interval list: chr, gene_start, gene_end  
gnomaD browser:16:89803958-89883066 (UCSC Annotation Interval)
my query interval:      16:89803957-89883065 (Ensembl)
Removed variants that did not pass filters (RF, AC0, InbreedingCoeff)
Filters that maybe redundant but here I removed variants that:
failed hard filters  (fail_hard_filters == True)
variant_type=='snv' & rf_probability >=0.1
variant_type=='indel' & rf_probability >=0.2

Final exome variant count: 5425 compared to an expectation of 4282 (Exomes + Shared)
In turn, when I apply the same filters for the genomes table (except rf_probability >= 0.4), the discrepancy is even larger with final variant set of 9481 variants compared to an expected count of ~1523 (Genomes 572 + Shared 951 -- see above)

I would really appreciate your input if I am missing any particular filters. I suspect that this might have something to do with allele frequencies or coverage depth. Should I be using the coverage table in some way and is that documented anywhere?

**Comment by nawatts** [comment]
Hi @nchambwe,

I suspect that the reason for the different variant counts is that the browser's gene page shows only variants in or within 75 base pairs of an exon. Thus, the query interval 16:89803957-89883065 will include many more intronic and UTR variants than the browser's gene page.

Including UTRs and non-coding transcripts on the FANCA page highlights the areas where the browser's gene page does not show variants.

<img width="1518" alt="Screen Shot 2019-06-27 at 3 35 52 PM" src="https://user-images.githubusercontent.com/1156625/60295431-ad16be80-98f1-11e9-8d8b-3aba5e3d61d2.png">

As compared to the region page for 16:89803958-89883066:

<img width="1510" alt="Screen Shot 2019-06-27 at 3 39 46 PM" src="https://user-images.githubusercontent.com/1156625/60295530-ef400000-98f1-11e9-8393-43ce4b45f7c0.png">
